/* Generated by scripts/generate-react95-icon-catalog.mjs — do not edit by hand. */
export type React95IconCategory =
  | 'files'
  | 'programs'
  | 'shell'
  | 'internet'
  | 'media'
  | 'mail'
  | 'tools'
  | 'other'

export type React95IconEntry = {
  id: string
  file: string
  category: React95IconCategory
}

export const REACT95_ICON_CATALOG: React95IconEntry[] = [
  {
    "id": "Access110",
    "file": "Access110_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access218",
    "file": "Access218_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access219",
    "file": "Access219_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access220",
    "file": "Access220_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access221",
    "file": "Access221_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access222",
    "file": "Access222_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access223",
    "file": "Access223_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access224",
    "file": "Access224_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access225",
    "file": "Access225_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access226",
    "file": "Access226_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access227",
    "file": "Access227_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access228",
    "file": "Access228_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access229",
    "file": "Access229_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Access230",
    "file": "Access230_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Accessibility",
    "file": "Accessibility_64x64_1.png",
    "category": "programs"
  },
  {
    "id": "Actmovie303",
    "file": "Actmovie303_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Addrbook",
    "file": "Addrbook_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Amovie2",
    "file": "Amovie2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Appwiz1500",
    "file": "Appwiz1500_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Appwiz1501",
    "file": "Appwiz1501_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Appwiz1502",
    "file": "Appwiz1502_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Appwiz1503",
    "file": "Appwiz1503_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "ArrowLeft",
    "file": "ArrowLeft_32x32_4.png",
    "category": "other"
  },
  {
    "id": "ArrowRight",
    "file": "ArrowRight_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Attach",
    "file": "Attach_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Awfext326049",
    "file": "Awfext326049_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfext326050",
    "file": "Awfext326050_16x16_4.png",
    "category": "programs"
  },
  {
    "id": "Awfext326051",
    "file": "Awfext326051_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfext326052",
    "file": "Awfext326052_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfext326053",
    "file": "Awfext326053_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxcg321301",
    "file": "Awfxcg321301_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxcg321302",
    "file": "Awfxcg321302_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxcg321303",
    "file": "Awfxcg321303_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxcg321304",
    "file": "Awfxcg321304_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxcg321305",
    "file": "Awfxcg321305_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32109",
    "file": "Awfxex32109_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32113",
    "file": "Awfxex32113_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32114",
    "file": "Awfxex32114_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32115",
    "file": "Awfxex32115_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32116",
    "file": "Awfxex32116_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32117",
    "file": "Awfxex32117_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32118",
    "file": "Awfxex32118_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32119",
    "file": "Awfxex32119_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32120",
    "file": "Awfxex32120_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32121",
    "file": "Awfxex32121_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32Awfxex",
    "file": "Awfxex32Awfxex_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awfxex32Info",
    "file": "Awfxex32Info_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Awschd32400",
    "file": "Awschd32400_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Awschd32401",
    "file": "Awschd32401_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Awschd32402",
    "file": "Awschd32402_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Awsnto3249",
    "file": "Awsnto3249_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Awsnto3250",
    "file": "Awsnto3250_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Back",
    "file": "Back_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Bat",
    "file": "Bat_32x32_4.png",
    "category": "other"
  },
  {
    "id": "BatExec",
    "file": "BatExec_32x32_4.png",
    "category": "other"
  },
  {
    "id": "BatExec2",
    "file": "BatExec2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "BatWait",
    "file": "BatWait_32x32_4.png",
    "category": "other"
  },
  {
    "id": "BillAdd",
    "file": "BillAdd_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Binoc",
    "file": "Binoc_16x16_4.png",
    "category": "other"
  },
  {
    "id": "BlankScreen100",
    "file": "BlankScreen100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Bold",
    "file": "Bold_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Bookmark",
    "file": "Bookmark_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Brush",
    "file": "Brush_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Bulb",
    "file": "Bulb_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Cachevu100",
    "file": "Cachevu100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "CalcSc",
    "file": "CalcSc_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Calculator",
    "file": "Calculator_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Camera",
    "file": "Camera_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ccapi104",
    "file": "Ccapi104_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ccapi105",
    "file": "Ccapi105_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ccapi106",
    "file": "Ccapi106_32x32_4.png",
    "category": "other"
  },
  {
    "id": "CdExe",
    "file": "CdExe_32x32_4.png",
    "category": "media"
  },
  {
    "id": "CdMusic",
    "file": "CdMusic_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Cdplayer107",
    "file": "Cdplayer107_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Cdplayer110",
    "file": "Cdplayer110_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Cdplayer114",
    "file": "Cdplayer114_32x32_1.png",
    "category": "media"
  },
  {
    "id": "CdSearch",
    "file": "CdSearch_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Centre",
    "file": "Centre_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Charmap1",
    "file": "Charmap1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Chatshow3000",
    "file": "Chatshow3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Circle",
    "file": "Circle_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Close",
    "file": "Close_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Columns",
    "file": "Columns_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Comctl32150",
    "file": "Comctl32150_32x32_1.png",
    "category": "other"
  },
  {
    "id": "Comdlg32528",
    "file": "Comdlg32528_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32529",
    "file": "Comdlg32529_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32530",
    "file": "Comdlg32530_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32531",
    "file": "Comdlg32531_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32532",
    "file": "Comdlg32532_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32533",
    "file": "Comdlg32533_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32534",
    "file": "Comdlg32534_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32535",
    "file": "Comdlg32535_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32536",
    "file": "Comdlg32536_91x36_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32537",
    "file": "Comdlg32537_98x30_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32538",
    "file": "Comdlg32538_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Comdlg32539",
    "file": "Comdlg32539_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Computer",
    "file": "Computer_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Computer2",
    "file": "Computer2_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Computer3",
    "file": "Computer3_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Computer4",
    "file": "Computer4_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Computer5",
    "file": "Computer5_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "ComputerFind",
    "file": "ComputerFind_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Confcp102",
    "file": "Confcp102_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp107",
    "file": "Confcp107_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp108",
    "file": "Confcp108_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp109",
    "file": "Confcp109_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp1100",
    "file": "Confcp1100_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp116",
    "file": "Confcp116_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp118",
    "file": "Confcp118_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Confcp120",
    "file": "Confcp120_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Conflnk102",
    "file": "Conflnk102_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Conflnk103",
    "file": "Conflnk103_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Controls3000",
    "file": "Controls3000_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Copy",
    "file": "Copy_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Coreui3000",
    "file": "Coreui3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "CurvesAndColors100",
    "file": "CurvesAndColors100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Cut",
    "file": "Cut_16x16_4.png",
    "category": "other"
  },
  {
    "id": "D3FlowerBox100",
    "file": "D3FlowerBox100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "D3FlyingObjectsIdApp",
    "file": "D3FlyingObjectsIdApp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "D3Maze100",
    "file": "D3Maze100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "D3PipesIdApp",
    "file": "D3PipesIdApp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "D3Text100",
    "file": "D3Text100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Data16",
    "file": "Data16_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Date",
    "file": "Date_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Defrag",
    "file": "Defrag_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag1",
    "file": "Defrag1_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag2",
    "file": "Defrag2_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag3",
    "file": "Defrag3_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag4",
    "file": "Defrag4_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag5",
    "file": "Defrag5_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag6",
    "file": "Defrag6_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag7",
    "file": "Defrag7_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag8",
    "file": "Defrag8_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Defrag9",
    "file": "Defrag9_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Delete",
    "file": "Delete_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Desk100",
    "file": "Desk100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Desktop",
    "file": "Desktop_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Detlicon",
    "file": "Detlicon_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Dial",
    "file": "Dial_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Dialer1",
    "file": "Dialer1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Dialer2",
    "file": "Dialer2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Dialmon200",
    "file": "Dialmon200_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Directcc1001",
    "file": "Directcc1001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Directcc1002",
    "file": "Directcc1002_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Directcc1003",
    "file": "Directcc1003_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Directcc1004",
    "file": "Directcc1004_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Directcc1005",
    "file": "Directcc1005_32x32_4.png",
    "category": "other"
  },
  {
    "id": "DirectccDirectcc",
    "file": "DirectccDirectcc_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Diskcopy1",
    "file": "Diskcopy1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Doc",
    "file": "Doc_16x16_4.png",
    "category": "other"
  },
  {
    "id": "DocGris",
    "file": "DocGris_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Download",
    "file": "Download_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Dpmodemx701",
    "file": "Dpmodemx701_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Drvspace1",
    "file": "Drvspace1_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace2",
    "file": "Drvspace2_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace3",
    "file": "Drvspace3_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace4",
    "file": "Drvspace4_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace5",
    "file": "Drvspace5_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace6",
    "file": "Drvspace6_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace7",
    "file": "Drvspace7_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Drvspace8",
    "file": "Drvspace8_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Earth",
    "file": "Earth_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Explore",
    "file": "Explore_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Explorer100",
    "file": "Explorer100_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer101",
    "file": "Explorer101_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer102",
    "file": "Explorer102_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer103",
    "file": "Explorer103_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer104",
    "file": "Explorer104_16x16_4.png",
    "category": "files"
  },
  {
    "id": "Explorer105",
    "file": "Explorer105_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer107",
    "file": "Explorer107_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Explorer108",
    "file": "Explorer108_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Expostrt128",
    "file": "Expostrt128_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Fave",
    "file": "Fave_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Fax",
    "file": "Fax_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Faxcover108",
    "file": "Faxcover108_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Faxcover140",
    "file": "Faxcover140_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Faxcover2",
    "file": "Faxcover2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Faxcover3",
    "file": "Faxcover3_32x32_4.png",
    "category": "other"
  },
  {
    "id": "FaxWarning",
    "file": "FaxWarning_32x32_4.png",
    "category": "other"
  },
  {
    "id": "FileCorrupted",
    "file": "FileCorrupted_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileDelete",
    "file": "FileDelete_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileFind",
    "file": "FileFind_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileFind2",
    "file": "FileFind2_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileFind3",
    "file": "FileFind3_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileFont",
    "file": "FileFont_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileFont2",
    "file": "FileFont2_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileIcons",
    "file": "FileIcons_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FilePen",
    "file": "FilePen_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FilePencil",
    "file": "FilePencil_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FilePick",
    "file": "FilePick_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FilePin",
    "file": "FilePin_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Files",
    "file": "Files_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileSettings",
    "file": "FileSettings_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileText",
    "file": "FileText_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileTextSettings",
    "file": "FileTextSettings_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FileTransfer",
    "file": "FileTransfer_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Filexfer128",
    "file": "Filexfer128_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Filexfer129",
    "file": "Filexfer129_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Filexfer130",
    "file": "Filexfer130_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FindArr",
    "file": "FindArr_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "FindDc2",
    "file": "FindDc2_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "FindDoc",
    "file": "FindDoc_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "FlyingThroughSpace100",
    "file": "FlyingThroughSpace100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "FlyingWindows100",
    "file": "FlyingWindows100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Fm20enu5",
    "file": "Fm20enu5_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Folder",
    "file": "Folder_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderExe",
    "file": "FolderExe_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderExe2",
    "file": "FolderExe2_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderFile",
    "file": "FolderFile_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderFont",
    "file": "FolderFont_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderOpen",
    "file": "FolderOpen_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderPrint",
    "file": "FolderPrint_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderRename",
    "file": "FolderRename_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderSettings",
    "file": "FolderSettings_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderSettings2",
    "file": "FolderSettings2_32x32_4.png",
    "category": "files"
  },
  {
    "id": "FolderShared",
    "file": "FolderShared_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Font",
    "file": "Font_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Font2",
    "file": "Font2_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "FontBig",
    "file": "FontBig_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Fontext1",
    "file": "Fontext1_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Fontext2",
    "file": "Fontext2_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Fontext3",
    "file": "Fontext3_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Fontext4",
    "file": "Fontext4_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "FontSml",
    "file": "FontSml_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Fontview110",
    "file": "Fontview110_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Fontview111",
    "file": "Fontview111_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "FontWid",
    "file": "FontWid_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Forbidden",
    "file": "Forbidden_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Format16",
    "file": "Format16_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Freecell1",
    "file": "Freecell1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Fte128",
    "file": "Fte128_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Fullscrn",
    "file": "Fullscrn_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Gcdef100",
    "file": "Gcdef100_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10001",
    "file": "Gcdef10001_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10002",
    "file": "Gcdef10002_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10003",
    "file": "Gcdef10003_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10004",
    "file": "Gcdef10004_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10005",
    "file": "Gcdef10005_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10006",
    "file": "Gcdef10006_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10007",
    "file": "Gcdef10007_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10008",
    "file": "Gcdef10008_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10009",
    "file": "Gcdef10009_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10010",
    "file": "Gcdef10010_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10011",
    "file": "Gcdef10011_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10012",
    "file": "Gcdef10012_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10013",
    "file": "Gcdef10013_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10014",
    "file": "Gcdef10014_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10015",
    "file": "Gcdef10015_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10016",
    "file": "Gcdef10016_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10017",
    "file": "Gcdef10017_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10018",
    "file": "Gcdef10018_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10019",
    "file": "Gcdef10019_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10020",
    "file": "Gcdef10020_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10021",
    "file": "Gcdef10021_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10022",
    "file": "Gcdef10022_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10023",
    "file": "Gcdef10023_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10024",
    "file": "Gcdef10024_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10025",
    "file": "Gcdef10025_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10026",
    "file": "Gcdef10026_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10027",
    "file": "Gcdef10027_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10028",
    "file": "Gcdef10028_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10029",
    "file": "Gcdef10029_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10030",
    "file": "Gcdef10030_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10031",
    "file": "Gcdef10031_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10032",
    "file": "Gcdef10032_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10033",
    "file": "Gcdef10033_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10034",
    "file": "Gcdef10034_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10035",
    "file": "Gcdef10035_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10036",
    "file": "Gcdef10036_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10037",
    "file": "Gcdef10037_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10038",
    "file": "Gcdef10038_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10039",
    "file": "Gcdef10039_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10040",
    "file": "Gcdef10040_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10041",
    "file": "Gcdef10041_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10042",
    "file": "Gcdef10042_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10043",
    "file": "Gcdef10043_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10044",
    "file": "Gcdef10044_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10045",
    "file": "Gcdef10045_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10046",
    "file": "Gcdef10046_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10047",
    "file": "Gcdef10047_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10048",
    "file": "Gcdef10048_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10049",
    "file": "Gcdef10049_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10050",
    "file": "Gcdef10050_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10051",
    "file": "Gcdef10051_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10052",
    "file": "Gcdef10052_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10053",
    "file": "Gcdef10053_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10054",
    "file": "Gcdef10054_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10055",
    "file": "Gcdef10055_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10056",
    "file": "Gcdef10056_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10057",
    "file": "Gcdef10057_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10058",
    "file": "Gcdef10058_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10059",
    "file": "Gcdef10059_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10060",
    "file": "Gcdef10060_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10061",
    "file": "Gcdef10061_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10062",
    "file": "Gcdef10062_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10063",
    "file": "Gcdef10063_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef10064",
    "file": "Gcdef10064_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef101",
    "file": "Gcdef101_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef102",
    "file": "Gcdef102_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef103",
    "file": "Gcdef103_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef104",
    "file": "Gcdef104_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef105",
    "file": "Gcdef105_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef106",
    "file": "Gcdef106_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef107",
    "file": "Gcdef107_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Gcdef108",
    "file": "Gcdef108_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef109",
    "file": "Gcdef109_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef110",
    "file": "Gcdef110_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef111",
    "file": "Gcdef111_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef112",
    "file": "Gcdef112_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef113",
    "file": "Gcdef113_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef114",
    "file": "Gcdef114_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef115",
    "file": "Gcdef115_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef116",
    "file": "Gcdef116_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef117",
    "file": "Gcdef117_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef122",
    "file": "Gcdef122_48x48_8.png",
    "category": "shell"
  },
  {
    "id": "Gcdef124",
    "file": "Gcdef124_64x64_4.png",
    "category": "shell"
  },
  {
    "id": "Globe",
    "file": "Globe_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Grpconv100",
    "file": "Grpconv100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Grpconv101",
    "file": "Grpconv101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Hand",
    "file": "Hand_32x32_4.png",
    "category": "other"
  },
  {
    "id": "HardwareDiag",
    "file": "HardwareDiag_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Help",
    "file": "Help_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "HelpBook",
    "file": "HelpBook_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "HelpPtr",
    "file": "HelpPtr_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "HtmlPage",
    "file": "HtmlPage_16x16_8.png",
    "category": "other"
  },
  {
    "id": "Icmui1200",
    "file": "Icmui1200_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Icmui1201",
    "file": "Icmui1201_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Icwdial101",
    "file": "Icwdial101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Icwdial102",
    "file": "Icwdial102_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ie",
    "file": "Ie_16x16_8.png",
    "category": "internet"
  },
  {
    "id": "Imgadmin214",
    "file": "Imgadmin214_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Imgedit10",
    "file": "Imgedit10_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Imgedit277",
    "file": "Imgedit277_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Imgscan10",
    "file": "Imgscan10_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Imgthumb10",
    "file": "Imgthumb10_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Inetcfg2300",
    "file": "Inetcfg2300_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Inetcfg2301",
    "file": "Inetcfg2301_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Inetcfg2302",
    "file": "Inetcfg2302_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Inetcfg2303",
    "file": "Inetcfg2303_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Inetcpl1301",
    "file": "Inetcpl1301_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1302",
    "file": "Inetcpl1302_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1303",
    "file": "Inetcpl1303_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1304",
    "file": "Inetcpl1304_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1305",
    "file": "Inetcpl1305_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1306",
    "file": "Inetcpl1306_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1307",
    "file": "Inetcpl1307_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1308",
    "file": "Inetcpl1308_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1309",
    "file": "Inetcpl1309_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1310",
    "file": "Inetcpl1310_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1311",
    "file": "Inetcpl1311_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1312",
    "file": "Inetcpl1312_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1313",
    "file": "Inetcpl1313_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1314",
    "file": "Inetcpl1314_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1315",
    "file": "Inetcpl1315_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1317",
    "file": "Inetcpl1317_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1318",
    "file": "Inetcpl1318_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1319",
    "file": "Inetcpl1319_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1320",
    "file": "Inetcpl1320_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl1321",
    "file": "Inetcpl1321_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Inetcpl4432",
    "file": "Inetcpl4432_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "InfoBubble",
    "file": "InfoBubble_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Install",
    "file": "Install_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Internat151",
    "file": "Internat151_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Intl101",
    "file": "Intl101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Isign32100",
    "file": "Isign32100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Isign324001",
    "file": "Isign324001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Isign32IcoApp",
    "file": "Isign32IcoApp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Issue",
    "file": "Issue_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Isuninst1000",
    "file": "Isuninst1000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Italic",
    "file": "Italic_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Jdbgmgr100",
    "file": "Jdbgmgr100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Jgdwmie101",
    "file": "Jgdwmie101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Job116",
    "file": "Job116_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Joy102",
    "file": "Joy102_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Joy108",
    "file": "Joy108_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Joy110",
    "file": "Joy110_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Justify",
    "file": "Justify_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Key",
    "file": "Key_32x32_4.png",
    "category": "other"
  },
  {
    "id": "KeyboardMouse",
    "file": "KeyboardMouse_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Keys",
    "file": "Keys_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Left",
    "file": "Left_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Lights100",
    "file": "Lights100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Lights101",
    "file": "Lights101_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Lights102",
    "file": "Lights102_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Lights103",
    "file": "Lights103_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Lights99",
    "file": "Lights99_256x96_4.png",
    "category": "other"
  },
  {
    "id": "Listicon",
    "file": "Listicon_16x16_4.png",
    "category": "other"
  },
  {
    "id": "LoaderBat",
    "file": "LoaderBat_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Lock",
    "file": "Lock_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Logo",
    "file": "Logo_32x32_4.png",
    "category": "other"
  },
  {
    "id": "LogView",
    "file": "LogView_32x32_4.png",
    "category": "other"
  },
  {
    "id": "LrgIcon",
    "file": "LrgIcon_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Lst2icon",
    "file": "Lst2icon_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Mail",
    "file": "Mail_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mail2",
    "file": "Mail2_16x16_4.png",
    "category": "mail"
  },
  {
    "id": "Mail3",
    "file": "Mail3_16x16_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews12",
    "file": "Mailnews12_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews13",
    "file": "Mailnews13_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews14",
    "file": "Mailnews14_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews15",
    "file": "Mailnews15_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews16",
    "file": "Mailnews16_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews17",
    "file": "Mailnews17_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews18",
    "file": "Mailnews18_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews19",
    "file": "Mailnews19_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews2",
    "file": "Mailnews2_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews20",
    "file": "Mailnews20_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews21",
    "file": "Mailnews21_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews22",
    "file": "Mailnews22_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews23",
    "file": "Mailnews23_16x16_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews3",
    "file": "Mailnews3_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews6",
    "file": "Mailnews6_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews7",
    "file": "Mailnews7_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews8",
    "file": "Mailnews8_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Mailnews9",
    "file": "Mailnews9_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Main100",
    "file": "Main100_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main103",
    "file": "Main103_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main104",
    "file": "Main104_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main105",
    "file": "Main105_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main106",
    "file": "Main106_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main107",
    "file": "Main107_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main200",
    "file": "Main200_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main300",
    "file": "Main300_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main400",
    "file": "Main400_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main500",
    "file": "Main500_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Main600",
    "file": "Main600_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Mapi32451",
    "file": "Mapi32451_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mapi32501",
    "file": "Mapi32501_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mapi32801",
    "file": "Mapi32801_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mapi32IconAttach",
    "file": "Mapi32IconAttach_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mapisp32100",
    "file": "Mapisp32100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mcdpkgtm3000",
    "file": "Mcdpkgtm3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mcm3200",
    "file": "Mcm3200_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mcm3201",
    "file": "Mcm3201_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mcm3202",
    "file": "Mcm3202_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mcm3203",
    "file": "Mcm3203_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mcm401",
    "file": "Mcm401_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mcm502",
    "file": "Mcm502_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "McmEarth",
    "file": "McmEarth_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "McmPhone",
    "file": "McmPhone_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Mdisp321",
    "file": "Mdisp321_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MediaAudio",
    "file": "MediaAudio_32x32_4.png",
    "category": "media"
  },
  {
    "id": "MediaCd",
    "file": "MediaCd_32x32_4.png",
    "category": "media"
  },
  {
    "id": "MediaVideo",
    "file": "MediaVideo_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Memory",
    "file": "Memory_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Message",
    "file": "Message_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Mic",
    "file": "Mic_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MicrosoftExchange",
    "file": "MicrosoftExchange_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MicrosoftNetwork",
    "file": "MicrosoftNetwork_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mipac",
    "file": "Mipac_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Mkcompat900",
    "file": "Mkcompat900_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mlcfg32129",
    "file": "Mlcfg32129_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mmsys100",
    "file": "Mmsys100_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys101",
    "file": "Mmsys101_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys102",
    "file": "Mmsys102_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys103",
    "file": "Mmsys103_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys104",
    "file": "Mmsys104_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys105",
    "file": "Mmsys105_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys106",
    "file": "Mmsys106_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys107",
    "file": "Mmsys107_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys108",
    "file": "Mmsys108_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys109",
    "file": "Mmsys109_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys110",
    "file": "Mmsys110_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys111",
    "file": "Mmsys111_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys112",
    "file": "Mmsys112_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys113",
    "file": "Mmsys113_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys114",
    "file": "Mmsys114_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys115",
    "file": "Mmsys115_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys116",
    "file": "Mmsys116_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys117",
    "file": "Mmsys117_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys118",
    "file": "Mmsys118_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys119",
    "file": "Mmsys119_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys120",
    "file": "Mmsys120_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys121",
    "file": "Mmsys121_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys122",
    "file": "Mmsys122_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys123",
    "file": "Mmsys123_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys124",
    "file": "Mmsys124_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys90",
    "file": "Mmsys90_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mmsys99",
    "file": "Mmsys99_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Moscudll128",
    "file": "Moscudll128_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mplayer10",
    "file": "Mplayer10_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer11",
    "file": "Mplayer11_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer110",
    "file": "Mplayer110_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer111",
    "file": "Mplayer111_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer112",
    "file": "Mplayer112_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer113",
    "file": "Mplayer113_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer114",
    "file": "Mplayer114_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer115",
    "file": "Mplayer115_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer116",
    "file": "Mplayer116_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer12",
    "file": "Mplayer12_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer13",
    "file": "Mplayer13_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer14",
    "file": "Mplayer14_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer15",
    "file": "Mplayer15_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mplayer16",
    "file": "Mplayer16_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Mprserv120",
    "file": "Mprserv120_48x48_4.png",
    "category": "other"
  },
  {
    "id": "Mprserv121",
    "file": "Mprserv121_48x48_4.png",
    "category": "other"
  },
  {
    "id": "Mprserv68",
    "file": "Mprserv68_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msacm3210",
    "file": "Msacm3210_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MsawtAwtIcon",
    "file": "MsawtAwtIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MsDos",
    "file": "MsDos_32x32_32.png",
    "category": "other"
  },
  {
    "id": "Msfs321951",
    "file": "Msfs321951_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mshearts1",
    "file": "Mshearts1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mshtml32528",
    "file": "Mshtml32528_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32529",
    "file": "Mshtml32529_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32534",
    "file": "Mshtml32534_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32535",
    "file": "Mshtml32535_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32536",
    "file": "Mshtml32536_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32537",
    "file": "Mshtml32537_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32538",
    "file": "Mshtml32538_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32539",
    "file": "Mshtml32539_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32540",
    "file": "Mshtml32540_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32541",
    "file": "Mshtml32541_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32542",
    "file": "Mshtml32542_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32543",
    "file": "Mshtml32543_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32544",
    "file": "Mshtml32544_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32545",
    "file": "Mshtml32545_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32546",
    "file": "Mshtml32546_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32547",
    "file": "Mshtml32547_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32548",
    "file": "Mshtml32548_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32549",
    "file": "Mshtml32549_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32550",
    "file": "Mshtml32550_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32551",
    "file": "Mshtml32551_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32552",
    "file": "Mshtml32552_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Mshtml32553",
    "file": "Mshtml32553_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Msnp32FolderIcon",
    "file": "Msnp32FolderIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnp32ServerIcon",
    "file": "Msnp32ServerIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnp32WrkgrpIcon",
    "file": "Msnp32WrkgrpIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnsetup1",
    "file": "Msnsetup1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnsign100",
    "file": "Msnsign100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnsign4001",
    "file": "Msnsign4001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MsnsignIcoApp",
    "file": "MsnsignIcoApp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnstart1",
    "file": "Msnstart1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnstart100",
    "file": "Msnstart100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnstart110",
    "file": "Msnstart110_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnstart120",
    "file": "Msnstart120_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msnsvc3000",
    "file": "Msnsvc3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mspaint",
    "file": "Mspaint_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating102",
    "file": "Msrating102_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating103",
    "file": "Msrating103_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating104",
    "file": "Msrating104_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating105",
    "file": "Msrating105_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating106",
    "file": "Msrating106_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating107",
    "file": "Msrating107_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating108",
    "file": "Msrating108_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msrating109",
    "file": "Msrating109_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Msvfw32943",
    "file": "Msvfw32943_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Mute",
    "file": "Mute_32x32_4.png",
    "category": "other"
  },
  {
    "id": "MystifyYourMind100",
    "file": "MystifyYourMind100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Netwatch101",
    "file": "Netwatch101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Network",
    "file": "Network_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Network2",
    "file": "Network2_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Network3",
    "file": "Network3_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "New",
    "file": "New_16x16_4.png",
    "category": "other"
  },
  {
    "id": "New16",
    "file": "New16_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Notepad",
    "file": "Notepad_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Notepad1",
    "file": "Notepad1_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Notepad2",
    "file": "Notepad2_32x32_4.png",
    "category": "files"
  },
  {
    "id": "NumPage",
    "file": "NumPage_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Nwnp32FolderIcon",
    "file": "Nwnp32FolderIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Nwnp32PrinterIcon",
    "file": "Nwnp32PrinterIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Nwnp32ServerIcon",
    "file": "Nwnp32ServerIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Nwnp32WrkgrpIcon",
    "file": "Nwnp32WrkgrpIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Oidis400Seqfileicon",
    "file": "Oidis400Seqfileicon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Oislb400DcScanIco",
    "file": "Oislb400DcScanIco_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Oiui400Imgstamp",
    "file": "Oiui400Imgstamp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Oiui400Textstamp",
    "file": "Oiui400Textstamp_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ole328",
    "file": "Ole328_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Open",
    "file": "Open_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Optional3000",
    "file": "Optional3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "OrderAs",
    "file": "OrderAs_16x16_4.png",
    "category": "other"
  },
  {
    "id": "OrderDs",
    "file": "OrderDs_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Packager",
    "file": "Packager_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Packager1",
    "file": "Packager1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "ParaBul",
    "file": "ParaBul_16x16_4.png",
    "category": "other"
  },
  {
    "id": "ParaNum",
    "file": "ParaNum_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Password100",
    "file": "Password100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Password1000",
    "file": "Password1000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Password1010",
    "file": "Password1010_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Paste",
    "file": "Paste_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Pbrush1",
    "file": "Pbrush1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Pen",
    "file": "Pen_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Person116",
    "file": "Person116_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Phone",
    "file": "Phone_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Phone2",
    "file": "Phone2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Playd16",
    "file": "Playd16_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Playp16",
    "file": "Playp16_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Plugin",
    "file": "Plugin_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Plugin2",
    "file": "Plugin2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Powercfg205",
    "file": "Powercfg205_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Powercfg210",
    "file": "Powercfg210_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Powercfg211",
    "file": "Powercfg211_32x32_4.png",
    "category": "other"
  },
  {
    "id": "PowerOff",
    "file": "PowerOff_32x32_4.png",
    "category": "other"
  },
  {
    "id": "PowerOn",
    "file": "PowerOn_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Print",
    "file": "Print_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Print2",
    "file": "Print2_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Printer",
    "file": "Printer_32x32_4.png",
    "category": "other"
  },
  {
    "id": "PrinterCalendar",
    "file": "PrinterCalendar_32x32_4.png",
    "category": "other"
  },
  {
    "id": "PrinterDrive",
    "file": "PrinterDrive_32x32_4.png",
    "category": "other"
  },
  {
    "id": "PrinterShared",
    "file": "PrinterShared_32x32_4.png",
    "category": "other"
  },
  {
    "id": "ProdinvMyicon",
    "file": "ProdinvMyicon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Progman1",
    "file": "Progman1_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman10",
    "file": "Progman10_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman11",
    "file": "Progman11_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman12",
    "file": "Progman12_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman13",
    "file": "Progman13_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman14",
    "file": "Progman14_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman15",
    "file": "Progman15_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman16",
    "file": "Progman16_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman17",
    "file": "Progman17_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman18",
    "file": "Progman18_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman19",
    "file": "Progman19_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman2",
    "file": "Progman2_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman20",
    "file": "Progman20_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman21",
    "file": "Progman21_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman22",
    "file": "Progman22_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman23",
    "file": "Progman23_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman24",
    "file": "Progman24_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman25",
    "file": "Progman25_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman26",
    "file": "Progman26_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman27",
    "file": "Progman27_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman28",
    "file": "Progman28_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman29",
    "file": "Progman29_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman3",
    "file": "Progman3_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman30",
    "file": "Progman30_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman31",
    "file": "Progman31_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman32",
    "file": "Progman32_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman33",
    "file": "Progman33_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman34",
    "file": "Progman34_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman35",
    "file": "Progman35_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman36",
    "file": "Progman36_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman37",
    "file": "Progman37_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman38",
    "file": "Progman38_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman39",
    "file": "Progman39_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman4",
    "file": "Progman4_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman40",
    "file": "Progman40_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman41",
    "file": "Progman41_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman42",
    "file": "Progman42_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman43",
    "file": "Progman43_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman44",
    "file": "Progman44_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman45",
    "file": "Progman45_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman46",
    "file": "Progman46_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman5",
    "file": "Progman5_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman6",
    "file": "Progman6_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman7",
    "file": "Progman7_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman8",
    "file": "Progman8_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Progman9",
    "file": "Progman9_32x32_4.png",
    "category": "programs"
  },
  {
    "id": "Props",
    "file": "Props_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Pshbtn",
    "file": "Pshbtn_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Qfecheck111",
    "file": "Qfecheck111_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Quartz100",
    "file": "Quartz100_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz101",
    "file": "Quartz101_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz102",
    "file": "Quartz102_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz103",
    "file": "Quartz103_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz200",
    "file": "Quartz200_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz201",
    "file": "Quartz201_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz202",
    "file": "Quartz202_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz203",
    "file": "Quartz203_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz300",
    "file": "Quartz300_32x32_4.png",
    "category": "media"
  },
  {
    "id": "Quartz301",
    "file": "Quartz301_32x32_4.png",
    "category": "media"
  },
  {
    "id": "QuestionBubble",
    "file": "QuestionBubble_32x32_32.png",
    "category": "other"
  },
  {
    "id": "Quikview1",
    "file": "Quikview1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Quikview2",
    "file": "Quikview2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Quikview3",
    "file": "Quikview3_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Quikview4",
    "file": "Quikview4_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Raplayer801",
    "file": "Raplayer801_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Rasapi32100",
    "file": "Rasapi32100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Rasapi32101",
    "file": "Rasapi32101_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Rasapi32102",
    "file": "Rasapi32102_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Rasapi32103",
    "file": "Rasapi32103_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Rasapi32104",
    "file": "Rasapi32104_32x32_4.png",
    "category": "other"
  },
  {
    "id": "ReaderCd",
    "file": "ReaderCd_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderCd2",
    "file": "ReaderCd2_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderClosed",
    "file": "ReaderClosed_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderDisket",
    "file": "ReaderDisket_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderDisket2",
    "file": "ReaderDisket2_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderDisketCasset",
    "file": "ReaderDisketCasset_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderEject",
    "file": "ReaderEject_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderNoshared",
    "file": "ReaderNoshared_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderOpened",
    "file": "ReaderOpened_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "ReaderShared",
    "file": "ReaderShared_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "RecycleEmpty",
    "file": "RecycleEmpty_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "RecycleFile",
    "file": "RecycleFile_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "RecycleFilefolder",
    "file": "RecycleFilefolder_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "RecycleFolder",
    "file": "RecycleFolder_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "RecycleFull",
    "file": "RecycleFull_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Redo",
    "file": "Redo_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Refresh",
    "file": "Refresh_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Regedit",
    "file": "Regedit_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit100",
    "file": "Regedit100_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit101",
    "file": "Regedit101_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit102",
    "file": "Regedit102_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit201",
    "file": "Regedit201_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit202",
    "file": "Regedit202_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit203",
    "file": "Regedit203_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit204",
    "file": "Regedit204_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit205",
    "file": "Regedit205_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regedit206",
    "file": "Regedit206_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Regwiz117",
    "file": "Regwiz117_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Regwiz122",
    "file": "Regwiz122_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Regwiz127",
    "file": "Regwiz127_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Regwiz129",
    "file": "Regwiz129_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Right",
    "file": "Right_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Rnaapp100",
    "file": "Rnaapp100_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp101",
    "file": "Rnaapp101_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp102",
    "file": "Rnaapp102_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp110",
    "file": "Rnaapp110_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp111",
    "file": "Rnaapp111_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp112",
    "file": "Rnaapp112_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp113",
    "file": "Rnaapp113_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaapp114",
    "file": "Rnaapp114_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Rnanp100",
    "file": "Rnanp100_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui100",
    "file": "Rnaui100_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui101",
    "file": "Rnaui101_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui102",
    "file": "Rnaui102_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui103",
    "file": "Rnaui103_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui104",
    "file": "Rnaui104_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui105",
    "file": "Rnaui105_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rnaui106",
    "file": "Rnaui106_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Rsrcmtr100",
    "file": "Rsrcmtr100_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr121",
    "file": "Rsrcmtr121_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr122",
    "file": "Rsrcmtr122_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr123",
    "file": "Rsrcmtr123_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr124",
    "file": "Rsrcmtr124_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr125",
    "file": "Rsrcmtr125_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr126",
    "file": "Rsrcmtr126_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr127",
    "file": "Rsrcmtr127_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr128",
    "file": "Rsrcmtr128_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr129",
    "file": "Rsrcmtr129_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr130",
    "file": "Rsrcmtr130_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr131",
    "file": "Rsrcmtr131_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr132",
    "file": "Rsrcmtr132_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rsrcmtr133",
    "file": "Rsrcmtr133_16x16_4.png",
    "category": "tools"
  },
  {
    "id": "Rundll1",
    "file": "Rundll1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Runonce106",
    "file": "Runonce106_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Save",
    "file": "Save_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Scandskw1",
    "file": "Scandskw1_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "SccviewIcon",
    "file": "SccviewIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "ScrollingMarquee100",
    "file": "ScrollingMarquee100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sendmail2001",
    "file": "Sendmail2001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Settings",
    "file": "Settings_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Setupslt3000",
    "file": "Setupslt3000_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Shdocvw256",
    "file": "Shdocvw256_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw257",
    "file": "Shdocvw257_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw258",
    "file": "Shdocvw258_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw259",
    "file": "Shdocvw259_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw260",
    "file": "Shdocvw260_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw261",
    "file": "Shdocvw261_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw262",
    "file": "Shdocvw262_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw272",
    "file": "Shdocvw272_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw273",
    "file": "Shdocvw273_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw274",
    "file": "Shdocvw274_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Shdocvw275",
    "file": "Shdocvw275_16x16_4.png",
    "category": "internet"
  },
  {
    "id": "Shell321",
    "file": "Shell321_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3210",
    "file": "Shell3210_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3211",
    "file": "Shell3211_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3212",
    "file": "Shell3212_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3213",
    "file": "Shell3213_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32133",
    "file": "Shell32133_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32134",
    "file": "Shell32134_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32135",
    "file": "Shell32135_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32136",
    "file": "Shell32136_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32137",
    "file": "Shell32137_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32138",
    "file": "Shell32138_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32139",
    "file": "Shell32139_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3214",
    "file": "Shell3214_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32140",
    "file": "Shell32140_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32141",
    "file": "Shell32141_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32142",
    "file": "Shell32142_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32143",
    "file": "Shell32143_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32144",
    "file": "Shell32144_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32145",
    "file": "Shell32145_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32146",
    "file": "Shell32146_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32147",
    "file": "Shell32147_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32148",
    "file": "Shell32148_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3215",
    "file": "Shell3215_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32151",
    "file": "Shell32151_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32152",
    "file": "Shell32152_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32153",
    "file": "Shell32153_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32154",
    "file": "Shell32154_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32155",
    "file": "Shell32155_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32156",
    "file": "Shell32156_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3216",
    "file": "Shell3216_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32160",
    "file": "Shell32160_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32161",
    "file": "Shell32161_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32165",
    "file": "Shell32165_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32166",
    "file": "Shell32166_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32167",
    "file": "Shell32167_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32168",
    "file": "Shell32168_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32169",
    "file": "Shell32169_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3217",
    "file": "Shell3217_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell32170",
    "file": "Shell32170_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3218",
    "file": "Shell3218_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3219",
    "file": "Shell3219_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell322",
    "file": "Shell322_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3220",
    "file": "Shell3220_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3221",
    "file": "Shell3221_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3222",
    "file": "Shell3222_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3223",
    "file": "Shell3223_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3224",
    "file": "Shell3224_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3225",
    "file": "Shell3225_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3226",
    "file": "Shell3226_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3227",
    "file": "Shell3227_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3228",
    "file": "Shell3228_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3229",
    "file": "Shell3229_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell323",
    "file": "Shell323_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3230",
    "file": "Shell3230_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3231",
    "file": "Shell3231_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3232",
    "file": "Shell3232_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3233",
    "file": "Shell3233_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3234",
    "file": "Shell3234_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3235",
    "file": "Shell3235_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3236",
    "file": "Shell3236_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3237",
    "file": "Shell3237_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3238",
    "file": "Shell3238_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3239",
    "file": "Shell3239_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell324",
    "file": "Shell324_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3240",
    "file": "Shell3240_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3241",
    "file": "Shell3241_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell3242",
    "file": "Shell3242_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell325",
    "file": "Shell325_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell326",
    "file": "Shell326_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell327",
    "file": "Shell327_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell328",
    "file": "Shell328_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shell329",
    "file": "Shell329_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Shortcut",
    "file": "Shortcut_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Shortcut2",
    "file": "Shortcut2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Shscrap100",
    "file": "Shscrap100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Signup",
    "file": "Signup_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Smmscrpt100",
    "file": "Smmscrpt100_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndrec3210",
    "file": "Sndrec3210_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndrec3215",
    "file": "Sndrec3215_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndrec3216",
    "file": "Sndrec3216_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndvol32300",
    "file": "Sndvol32300_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndvol32301",
    "file": "Sndvol32301_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndvol32302",
    "file": "Sndvol32302_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndvol32303",
    "file": "Sndvol32303_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sndvol32304",
    "file": "Sndvol32304_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Sol1",
    "file": "Sol1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Spellchk",
    "file": "Spellchk_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Star",
    "file": "Star_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Svrworld",
    "file": "Svrworld_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Swinst53000",
    "file": "Swinst53000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Syncui120",
    "file": "Syncui120_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui121",
    "file": "Syncui121_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui122",
    "file": "Syncui122_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui123",
    "file": "Syncui123_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui124",
    "file": "Syncui124_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui125",
    "file": "Syncui125_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui126",
    "file": "Syncui126_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui127",
    "file": "Syncui127_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui128",
    "file": "Syncui128_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui129",
    "file": "Syncui129_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui130",
    "file": "Syncui130_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui131",
    "file": "Syncui131_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui132",
    "file": "Syncui132_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Syncui135",
    "file": "Syncui135_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Sysedit1",
    "file": "Sysedit1_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Sysedit2",
    "file": "Sysedit2_64x64_1.png",
    "category": "tools"
  },
  {
    "id": "Sysmon1000",
    "file": "Sysmon1000_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "SysPackage",
    "file": "SysPackage_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Systray200",
    "file": "Systray200_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray210",
    "file": "Systray210_16x16_4.png",
    "category": "shell"
  },
  {
    "id": "Systray220",
    "file": "Systray220_16x16_4.png",
    "category": "shell"
  },
  {
    "id": "Systray221",
    "file": "Systray221_16x16_4.png",
    "category": "shell"
  },
  {
    "id": "Systray300",
    "file": "Systray300_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray301",
    "file": "Systray301_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray302",
    "file": "Systray302_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray303",
    "file": "Systray303_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray304",
    "file": "Systray304_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray305",
    "file": "Systray305_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Systray306",
    "file": "Systray306_32x32_4.png",
    "category": "shell"
  },
  {
    "id": "Taskman100",
    "file": "Taskman100_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Textchat",
    "file": "Textchat_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Textchat2",
    "file": "Textchat2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Tick",
    "file": "Tick_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Time",
    "file": "Time_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Timedate",
    "file": "Timedate_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Timedate200",
    "file": "Timedate200_32x32_4.png",
    "category": "other"
  },
  {
    "id": "TimerFont",
    "file": "TimerFont_32x32_4.png",
    "category": "tools"
  },
  {
    "id": "Toupper",
    "file": "Toupper_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Tour1",
    "file": "Tour1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Tree",
    "file": "Tree_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Tssoft3210",
    "file": "Tssoft3210_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Twunk32TwunkIcon",
    "file": "Twunk32TwunkIcon_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ulclient1002",
    "file": "Ulclient1002_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Ulclient1235",
    "file": "Ulclient1235_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Underlne",
    "file": "Underlne_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Undo",
    "file": "Undo_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Uninst1000",
    "file": "Uninst1000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Uninstall",
    "file": "Uninstall_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Unmute",
    "file": "Unmute_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Url102",
    "file": "Url102_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url103",
    "file": "Url103_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url104",
    "file": "Url104_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url105",
    "file": "Url105_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url1102",
    "file": "Url1102_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url1103",
    "file": "Url1103_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url1104",
    "file": "Url1104_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Url1105",
    "file": "Url1105_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "User",
    "file": "User_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User1",
    "file": "User1_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User2",
    "file": "User2_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User3",
    "file": "User3_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User4",
    "file": "User4_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User5",
    "file": "User5_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User6",
    "file": "User6_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "User7",
    "file": "User7_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Voxplay3000",
    "file": "Voxplay3000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Vvexe321",
    "file": "Vvexe321_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wab321010",
    "file": "Wab321010_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321011",
    "file": "Wab321011_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321012",
    "file": "Wab321012_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321013",
    "file": "Wab321013_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321014",
    "file": "Wab321014_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321015",
    "file": "Wab321015_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321016",
    "file": "Wab321016_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321017",
    "file": "Wab321017_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321018",
    "file": "Wab321018_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321019",
    "file": "Wab321019_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wab321020",
    "file": "Wab321020_32x32_4.png",
    "category": "mail"
  },
  {
    "id": "Wangimg128",
    "file": "Wangimg128_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wangimg129",
    "file": "Wangimg129_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wangimg130",
    "file": "Wangimg130_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Warning",
    "file": "Warning_32x32_4.png",
    "category": "other"
  },
  {
    "id": "WebLink",
    "file": "WebLink_16x16_4.png",
    "category": "other"
  },
  {
    "id": "WebOpen",
    "file": "WebOpen_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Websrch",
    "file": "Websrch_16x16_4.png",
    "category": "other"
  },
  {
    "id": "WebTxfr",
    "file": "WebTxfr_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Wgpocpl128",
    "file": "Wgpocpl128_32x32_4.png",
    "category": "other"
  },
  {
    "id": "What",
    "file": "What_16x16_4.png",
    "category": "other"
  },
  {
    "id": "WindowAbc",
    "file": "WindowAbc_32x32_4.png",
    "category": "other"
  },
  {
    "id": "WindowAccessibility",
    "file": "WindowAccessibility_32x32_4.png",
    "category": "other"
  },
  {
    "id": "WindowGraph",
    "file": "WindowGraph_32x32_4.png",
    "category": "other"
  },
  {
    "id": "WindowsExplorer",
    "file": "WindowsExplorer_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winfile1",
    "file": "Winfile1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winfile2",
    "file": "Winfile2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winfile3",
    "file": "Winfile3_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winfile4",
    "file": "Winfile4_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winhlp324000",
    "file": "Winhlp324000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winhlp324001",
    "file": "Winhlp324001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winhlp324002",
    "file": "Winhlp324002_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wininet32546",
    "file": "Wininet32546_32x32_4.png",
    "category": "internet"
  },
  {
    "id": "Winmine1",
    "file": "Winmine1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winpopup1",
    "file": "Winpopup1_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winpopup2",
    "file": "Winpopup2_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Winpopup3",
    "file": "Winpopup3_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wintrust103",
    "file": "Wintrust103_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui321000",
    "file": "Wmsui321000_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui321001",
    "file": "Wmsui321001_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui321306",
    "file": "Wmsui321306_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322219",
    "file": "Wmsui322219_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322220",
    "file": "Wmsui322220_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322221",
    "file": "Wmsui322221_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322223",
    "file": "Wmsui322223_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322224",
    "file": "Wmsui322224_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322225",
    "file": "Wmsui322225_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui322226",
    "file": "Wmsui322226_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323911",
    "file": "Wmsui323911_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323912",
    "file": "Wmsui323912_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323919",
    "file": "Wmsui323919_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323920",
    "file": "Wmsui323920_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323924",
    "file": "Wmsui323924_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323926",
    "file": "Wmsui323926_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323929",
    "file": "Wmsui323929_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323934",
    "file": "Wmsui323934_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323935",
    "file": "Wmsui323935_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323936",
    "file": "Wmsui323936_16x16_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui323938",
    "file": "Wmsui323938_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325084",
    "file": "Wmsui325084_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325085",
    "file": "Wmsui325085_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325086",
    "file": "Wmsui325086_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325087",
    "file": "Wmsui325087_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325900",
    "file": "Wmsui325900_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wmsui325901",
    "file": "Wmsui325901_32x32_4.png",
    "category": "other"
  },
  {
    "id": "Wordpad",
    "file": "Wordpad_32x32_4.png",
    "category": "files"
  },
  {
    "id": "Write1",
    "file": "Write1_32x32_4.png",
    "category": "files"
  }
]
